### ISSUE TITLE
Reader does not show evidence of the "choice" Schema Components

### ISSUE THREAD

**Issue by samlikins** [goetas-webservices/wsdl-reader#6]
WSDL files can utilize the ["choice" Schema Components](https://www.w3.org/TR/2004/REC-xmlschema-1-20041028/structures.html#element-choice) (much like the "sequence" Schema Component); however the data structure produced by this library doesn't seem to provide evidence of there being any choice at all.  Is this an oversight or a deliberate design decision?

**Comment by goetas** [comment]
It is simply not supported yet. See https://github.com/goetas-webservices/xsd-reader/issues/7

PHP itself does not offer anything similar that can allow us to express choice/sequence XSD type definitions. 

The related feature request most likely will not be implemented until someone doesn't have an idea on how implement choice/sequence in php first.

I'm closing this ticket as I consider the question as answered. If you have an idea on how to implement this, feel free to comment on the related Ticket
